/** Tokens extraídos de elite_loyalty_system (light) e aureum_elite (dark) — Stitch FRIK */

export const lightThemeVars: Record<string, string> = {
  "--background": "#faf9f6",
  "--surface": "#faf9f6",
  "--surface-bright": "#faf9f6",
  "--surface-dim": "#dbdad7",
  "--surface-container": "#efeeeb",
  "--surface-container-low": "#f4f3f1",
  "--surface-container-high": "#e9e8e5",
  "--surface-container-highest": "#e3e2e0",
  "--surface-container-lowest": "#ffffff",
  "--surface-variant": "#e3e2e0",
  "--on-background": "#1a1c1a",
  "--on-surface": "#1a1c1a",
  "--on-surface-variant": "#504538",
  "--primary": "#825503",
  "--on-primary": "#ffffff",
  "--primary-container": "#cc9544",
  "--on-primary-container": "#4d3000",
  "--primary-fixed": "#ffddb3",
  "--primary-fixed-dim": "#f8bc66",
  "--secondary": "#635e54",
  "--on-secondary": "#ffffff",
  "--secondary-container": "#e6dfd2",
  "--on-secondary-container": "#676258",
  "--secondary-fixed": "#e9e2d5",
  "--secondary-fixed-dim": "#cdc6b9",
  "--tertiary": "#645e53",
  "--tertiary-container": "#a69e92",
  "--outline": "#827566",
  "--outline-variant": "#d4c4b2",
  "--error": "#ba1a1a",
  "--error-container": "#ffdad6",
  "--card-cream": "#f2e8da",
  "--font-sans": "'Hanken Grotesk', system-ui, sans-serif",
};

export const darkThemeVars: Record<string, string> = {
  "--background": "#141312",
  "--surface": "#141312",
  "--surface-bright": "#3a3937",
  "--surface-dim": "#141312",
  "--surface-container": "#201f1e",
  "--surface-container-low": "#1c1b1a",
  "--surface-container-high": "#2b2a28",
  "--surface-container-highest": "#363533",
  "--surface-container-lowest": "#0f0e0d",
  "--surface-variant": "#363533",
  "--on-background": "#e5e2df",
  "--on-surface": "#e5e2df",
  "--on-surface-variant": "#d4c4b2",
  "--primary": "#f8bc66",
  "--on-primary": "#452b00",
  "--primary-container": "#cc9544",
  "--on-primary-container": "#4d3000",
  "--primary-fixed": "#ffddb3",
  "--primary-fixed-dim": "#f8bc66",
  "--secondary": "#d4c3b9",
  "--on-secondary": "#382e27",
  "--secondary-container": "#52473f",
  "--on-secondary-container": "#c5b5ab",
  "--secondary-fixed": "#f0dfd4",
  "--secondary-fixed-dim": "#d4c3b9",
  "--tertiary": "#d7c3b4",
  "--tertiary-container": "#af9c8f",
  "--outline": "#9d8e7e",
  "--outline-variant": "#504538",
  "--error": "#ffb4ab",
  "--error-container": "#93000a",
  "--card-cream": "#2a211a",
  "--font-sans": "'Plus Jakarta Sans', system-ui, sans-serif",
};
